/*!
 * lang.en.v1.js - English for シナリオテキストメーカー (Scenario Text Maker).
 * Keys are the Japanese texts of the page and scripts (see i18n.v1.js).
 * CCFOLIA terms follow CCFOLIA's own English UI; OBS terms follow OBS's.
 */
I18n.add("en", {
  "シナリオテキストメーカー | ココフォリア": "Scenario Text Maker | CCFOLIA",
  "‹ shiki365 のツール置き場": "‹ shiki365's tools",
  "シナリオテキストメーカー": "Scenario Text Maker",
  "台本や描写の文章を貼ると、ココフォリアの「シナリオテキスト」をまとめて作ります。できたファイルをルームデータとして読み込むだけで、シナリオテキスト一覧に並びます。台詞には話し手の立ち絵（表情の差分も）を、描写やハンドアウトには 1 件ずつ好きな画像を付けられ、シナリオテキストから送るとメッセージボックスに画像が出ます。すべてブラウザの中だけで処理され、入力した内容や画像がどこかに送られることはありません。マシュマロでいただいた要望から生まれたツールです。": "Paste a script or descriptions and it makes CCFOLIA \"Scenario texts\" in one go. Import the file as room data and they line up in the scenario text list. Lines can carry the speaker's portrait (with expressions), and descriptions or handouts any picture you like, which shows in the message box when sent from the scenario texts. Everything runs in your browser; nothing you enter and no image is sent anywhere. This tool was born from a request sent through Marshmallow.",
  "作り方": "How to split",
  "台本（台詞を 1 件ずつ）": "Script (one entry per line of dialogue)",
  "「アリス「こんにちは」」のような台本を、台詞ごとに分けます。タイトルは話し手の名前になります。": "Splits a script such as Alice \"Hello\" into one entry per line. The title is the speaker's name.",
  "見出しで区切る（描写・情報）": "Split at headings (descriptions, information)",
  "「■図書館」のような見出しごとに分けます。タイトルは見出し、本文はその下の文です。探索箇所の描写やハンドアウトに。": "Splits at headings such as \"■ Library\". The heading is the title and the lines below it are the text. For location descriptions and handouts.",
  "画像の置き場（": "Image shelf (",
  "枚）": "images)",
  "立ち絵やハンドアウトの絵をここに入れておくと、話し手の立ち絵や、1 件ずつの画像としてプルダウンで選べます。<b>画像の名前と同じ見出しや話し手には、自動でその画像が付きます</b>（「■鍵」と書けば、「鍵」という名前の画像）。画像ごとに「出典・作者」のメモも付けられます（まとめて保存する一覧に入ります）。画像はこのブラウザの中に保存されます。": "Put portraits and handout pictures here to choose them from the menus as a speaker's portrait or as the picture of a single entry. <b>A heading or speaker with the same name as an image gets that image automatically</b> (\"■ Key\" gets the image named \"Key\"). Each image can carry a \"source / author\" note (it goes into the list saved with the images). Images are kept inside this browser.",
  "ここに画像をドラッグ＆ドロップ／クリックして選ぶ（何枚でも）": "Drop images here, or click to choose (any number)",
  "PNG・JPEG・GIF・WebP 1 枚 5 MB まで": "PNG, JPEG, GIF, WebP; up to 5 MB each",
  "URL で追加": "Add by URL",
  "置き場の画像 1 枚につき、シナリオテキストを 1 件、一覧の最後に足します": "Adds one scenario text at the end of the list for each image on the shelf",
  "画像ごとに 1 件作る": "One entry per image",
  "話し手（立ち絵）": "Speakers (portraits)",
  "人物と立ち絵を登録します（立ち絵がいらなければ、登録しなくても作れます）。<b>名前</b>は、ココフォリアで送ったときに表示される名前（シナリオテキストのタイトル）になります。立ち絵は置き場の画像から選ぶか、「＋ 画像」で追加します（左の枠に画像をドロップしても設定できます）。表情ごとの画像は「差分」に登録するか、置き場に「アリス_笑顔」のような名前で入れて「置き場から差分を作る」を押します。立ち絵から、シルエット・セピアなどの<b>演出差分</b>も作れます（立ち絵を加工するので、描いた人が加工を認めている立ち絵だけに使ってください。動く画像は最初のコマだけ）。台本に「アリス（笑顔）「…」」か「アリス@笑顔「…」」と書くと切り替わります。": "Register people and their portraits (without portraits you can skip this). <b>The name</b> is the name shown when sent in CCFOLIA (the scenario text's title). Choose the portrait from the shelf or add one with \"+ Image\" (dropping an image on the box at the left works too). For a picture per expression, register \"expressions\", or put images named like \"Alice_smile\" on the shelf and press \"Expressions from the shelf\". <b>Effect expressions</b> such as a silhouette or sepia can be made from the portrait (this alters the portrait, so use it only where the artist allows editing; a moving image gives its first frame only). Write Alice (smile) \"…\" or Alice@smile \"…\" in the script to switch.",
  "＋ 話し手を追加": "+ Add a speaker",
  "差分の名前をタイトルにも付ける（例: アリス（笑顔））": "Add the expression to the title too (e.g. Alice (smile))",
  "オフなら、差分を選んでもタイトルは「アリス」のまま（立ち絵だけ変わる）。オンなら、ココフォリアでも「アリス（笑顔）」と表示されます。手直しで打ったタイトルは変わりません。": "Off: the title stays \"Alice\" whatever the expression (only the portrait changes). On: CCFOLIA shows \"Alice (smile)\" too. Titles you typed by hand do not change.",
  "読み取り方": "Reading the text",
  "1 件の区切り": "One entry is",
  "1 行ずつ（「」が閉じるまでは続ける）": "One line (an open quote continues on the next lines)",
  "空行で区切ったまとまりごと": "A block between blank lines",
  "話し手の書き方": "How speakers are written",
  "自動（名前「台詞」／登録した名前：台詞）": "Auto (Name \"line\" / Registered name: line)",
  "名前「台詞」だけ": "Name \"line\" only",
  "名前：台詞 だけ": "Name: line only",
  "台詞の「」を残す": "Keep the quotation marks",
  "地の文": "Narration",
  "シナリオテキストに入れる": "Include as scenario texts",
  "入れない（台詞だけ）": "Leave out (dialogue only)",
  "地の文の名前": "Name for narration",
  "空なら、送るときの名前の欄の名前": "Empty: the name in the name field when sending",
  "見出しは「■」「□」「◆」「●」「★」などの記号で始まる行、「【図書館】」のように【】だけの行、「## 図書館」のように # で始まる行です。見出しが登録した話し手の名前なら、その立ち絵が付きます。置き場の画像の名前と同じなら、その画像が付きます。": "A heading is a line that starts with a mark such as ■ □ ◆ ● ★, a line that is only 【Library】, or a line that starts with # such as \"## Library\". A heading that is a registered speaker's name gets that portrait; one that matches an image on the shelf gets that image.",
  "名前を空にすると、送るときに名前の欄に入っている名前（いつも GM が使っている名前など）で送られます。話し手として登録した名前にすると、その立ち絵も付きます。": "With an empty name, it is sent under whatever name is in the name field at that moment (the name the GM usually uses, for example). With a registered speaker's name, that portrait is added too.",
  "保存": "Save",
  "プロジェクトを保存": "Save project",
  "プロジェクトを開く": "Open project",
  "最初からやり直す": "Start over",
  "話し手と文章、置き場の画像は、このブラウザに自動で保存されます。別の PC やブラウザに移すときは「プロジェクトを保存」を使ってください（置き場の画像もファイルに入ります）。": "Speakers, text and the shelf's images are saved in this browser automatically. To move to another PC or browser, use \"Save project\" (the shelf's images go into the file too).",
  "台本": "Script",
  "例を入れる": "Insert an example",
  "できあがり（": "Result (",
  "件）": "entries)",
  "一覧を手直ししています。文章や読み取り方を変えても、一覧はこのままです。": "The list has been edited by hand. Changing the text or how it is read no longer changes the list.",
  "文章から作り直す": "Rebuild from the text",
  "一覧をクリックすると、シナリオテキスト一覧から送ったときの見え方（ココフォリアのメッセージボックスと、チャット欄）と、手直しの欄が出ます。<b>立ち絵は、幅が決まっていて、高さが画像の形で決まります</b>（縦長は大きく、横長は小さく出ます）。": "Click an entry to see how it looks when sent from the scenario text list (CCFOLIA's message box and chat log) and to edit it. <b>The portrait has a fixed width, and its height follows the image's shape</b> (tall images come out large, wide ones small).",
  "ココフォリアを開く画面の広さ": "Screen width CCFOLIA is opened in",
  "パソコン（立ち絵の幅 240px）": "Computer (portrait 240 px wide)",
  "小さい画面・幅 900px 未満（180px）": "Small screen, under 900 px wide (180 px)",
  "スマホ・幅 600px 未満（120px）": "Phone, under 600 px wide (120 px)",
  "メッセージボックスの見本": "Message box preview",
  "一覧から 1 件を選ぶと、ここに見え方が出ます": "Choose an entry from the list to see it here",
  "チャット欄（ログ）では、約 40px 四方のアイコンになります（縦長は上の部分、横長は中央が切り取られます）": "In the chat log it becomes an icon of about 40 px square (the top of a tall image, the middle of a wide one)",
  "行": "Line",
  "画像": "Image",
  "タイトル（名前）": "Title (name)",
  "本文": "Text",
  "選んだ 1 件を手直し（画像をここにドロップすると、この 1 件の画像になります）": "Edit the chosen entry (drop an image here to make it this entry's image)",
  "空なら名前の欄の名前": "Empty: the name in the name field",
  "話し手の名前に戻す": "Back to the speaker's name",
  "話し手": "Speaker",
  "差分 ": "Expression ",
  "画像（この 1 件だけ）": "Image (this entry only)",
  "この 1 件の画像をファイルから追加": "Add this entry's image from a file",
  "＋ 画像": "+ Image",
  "↑ 上へ": "↑ Up",
  "↓ 下へ": "↓ Down",
  "＋ 下に 1 件足す": "+ Add one below",
  "この 1 件を削除": "Delete this entry",
  "確定して、次の文章へ": "Confirm and go on to the next text",
  "たくさん作るときは、ここで「確定」すると今の一覧が下に残り、文章の欄が空になります。続けて次の台本や描写を入れられます。": "When making many, \"Confirm\" keeps the current list below and empties the text box, so you can go on with the next script or description.",
  "確定したシナリオテキスト（": "Confirmed scenario texts (",
  "書き出し": "Export",
  "ルームデータ（ZIP）を書き出す": "Export room data (ZIP)",
  "使っている画像をまとめて保存（ZIP）": "Save the images in use together (ZIP)",
  "置き場のすべての画像を入れる": "Include every image on the shelf",
  "書き出したルームデータの中の画像は、ファイル名が長い英数字（中身の識別子）になっています。こちらは、置き場の名前で読める形に並べ、「画像の一覧.txt」に、どのシナリオテキストで使っているか・出典のメモ・ルームデータ内のファイル名の対応を書きます。URL の画像は、ブラウザの制限で中身を入れられないので、URL だけ書きます。": "Inside the exported room data, image files have long alphanumeric names (identifiers of their contents). This saves them under their shelf names instead, with \"image-list.txt\" telling which scenario texts use each one, its source note, and its file name inside the room data. Images given by URL cannot be included (a browser restriction), so only the URL is written.",
  "ココフォリアでの読み込みかた": "Importing into CCFOLIA",
  "ルームに <b>GM（ルームマスター・サブルームマスター）</b>として入る。ゲストのログインでは読み込めません": "Enter the room as <b>a GM (Room Master or Sub-room master)</b>. A guest login cannot import.",
  "左上のルーム名 →「ルーム設定」→「ルームデータ」→「ルームデータのインポート」の「インポート」で、書き出した ZIP を選ぶ（盤面に ZIP をドラッグ＆ドロップしても読み込めます）": "Room name at the top left → \"Room settings\" → \"Room data\" → \"Import\" under \"Import room data\", and choose the exported ZIP (dropping the ZIP on the board works too).",
  "「外部ツールで作成および編集されたデータです。信頼できるデータのみ取り込むようにしてください。」と出るので、このツールで作ったものなら OK。<b>このツールのデータは、いつもこの確認が出ます</b>": "It says \"Data created and edited by external tools. Only import reliable data.\" If the file was made with this tool, press OK. <b>Data from this tool always shows this notice.</b>",
  "上のメニューの「[GM] シナリオテキスト一覧」に、台本の順に並んでいます。開いて「送信」すると、タイトルの名前で送られ、メッセージボックスに立ち絵が出ます": "They are in \"[GM] Scenario text list\" in the top menu, in the order of the script. Open one and press \"Send\": it is sent under its title as the name, and the portrait appears in the message box.",
  "知っておいてほしいこと": "Good to know",
  "読み込むとシナリオテキストが<b>追加</b>されます。すでにあるシナリオテキストやキャラクター、盤面は変わりません。いらなくなったら、シナリオテキスト一覧から削除してください": "Importing <b>adds</b> scenario texts. Existing scenario texts, characters and the board do not change. Delete them from the scenario text list when you no longer need them.",
  "立ち絵が出るのは、シナリオテキスト一覧から「送信」したときです。送信欄に打って送ると、ふつうの発言（名前の欄のキャラクター）になります": "The portrait appears when you press \"Send\" in the scenario text list. Typing into the chat box and sending makes an ordinary message (the character in the name field).",
  "置き場の画像は、このブラウザの中にだけ保存されます（ブラウザのサイトデータを消すと消えます）。大事なものは「プロジェクトを保存」でファイルにも残してください": "The shelf's images are kept only inside this browser (clearing the browser's site data removes them). Keep important ones in a file too with \"Save project\".",
  "画像は読み込んだときにココフォリアへアップロードされます（ルームデータの画像と同じ共有の置き場）。<b>ほかの人の立ち絵を使うときは、描いた人の許可の範囲で</b>": "Images are uploaded to CCFOLIA when imported (to the same shared storage as other room data images). <b>Use other people's portraits only within what the artist permits.</b>",
  "自分で作ったルームで使ってください。購入したシナリオ（CCFOLIA GAMES など）のルームデータは、改変が禁止されています": "Use it in rooms you made yourself. Room data of purchased scenarios (CCFOLIA GAMES and the like) must not be modified.",
  "ココフォリアの非公式のツールです。ココフォリアのアップデートで、読み込めなくなることがあります": "An unofficial tool for CCFOLIA. A CCFOLIA update may stop the files from importing.",
  "OBS に映すなら": "Showing it in OBS",
  "メッセージボックスを配信画面に映すには、<a href=\"https://shiki365.github.io/message-box-maker/\">メッセージボックスメーカー</a>で作ったカスタム CSS と組み合わせてください。": "To show the message box on stream, combine this with the Custom CSS made by the <a href=\"https://shiki365.github.io/message-box-maker/\">Message Box Maker</a>.",
  "ブラウザだけで動く無料ツールです。作ったデータは自由に使えます。": "A free tool that runs in your browser. Use the data you make freely.",
  "ココフォリアのデータの形が変わると、読み込めなくなることがあります。いずれのサービスとも関係のない<strong>非公式</strong>のツールです。": "If CCFOLIA's data format changes, the files may stop importing. It is an <strong>unofficial</strong> tool, not connected with any service.",
  "ほかのツールも見る（shiki365 のツール置き場）": "More tools (shiki365's tools)",
  "・": "·",
  "不具合の報告・感想": "Report a bug / feedback",
  "ほしいツールの要望（マシュマロ）": "Request a tool (Marshmallow)",
  "開発を応援する（BOOTH）": "Support the development (BOOTH)",
  "最終更新": "Last updated",
  "{title}（{face}）": "{title} ({face})",
  "、": ", ",
  "アリス「ねえ、この屋敷、本当に誰も住んでいないの？」\nボブ「そのはずだよ。十年前から空き家だって」\n扉の向こうから、かすかに足音が聞こえる。\nアリス（不安）「……今の、聞こえた？」\nボブ：気のせいだと思いたいね": "Alice \"Hey, does nobody really live in this house?\"\nBob \"That's what they say. It has been empty for ten years.\"\nFrom beyond the door comes the faint sound of footsteps.\nAlice (uneasy) \"...Did you hear that just now?\"\nBob: I'd like to think it was my imagination.",
  "■図書館\n古い新聞が棚にぎっしりと並んでいる。\n〈図書館〉に成功すると、十年前の火事の記事が見つかる。\n\n■書斎\n机の上に、鍵のかかった小箱がひとつ置かれている。\n\n■アリス\n（アリスからの手紙）明日の夜、屋敷の裏口で待っています。": "■ Library\nOld newspapers are packed tightly on the shelves.\nA successful Library Use roll finds an article about the fire ten years ago.\n\n■ Study\nA small locked box sits on the desk.\n\n■ Alice\n(A letter from Alice) I will be waiting at the back door of the mansion tomorrow night.",
  "アリス": "Alice",
  "ボブ": "Bob",
  "ブラウザに自動保存できませんでした。「プロジェクトを保存」でファイルに残してください。": "Could not autosave in the browser. Keep your work in a file with \"Save project\".",
  "画像をブラウザに保存できませんでした。このページを閉じると消えるので、「プロジェクトを保存」でファイルに残してください。": "The image could not be saved in the browser. It is lost when this page closes, so keep it in a file with \"Save project\".",
  "URL の画像": "Image by URL",
  "画像を {n} 枚、置き場に入れました。": "Put {n} image(s) on the shelf. ",
  "ただし、このブラウザでは画像を保存できないので、閉じる前に「プロジェクトを保存」でファイルに残してください。": "This browser cannot keep images, though, so save them to a file with \"Save project\" before closing. ",
  "{n} 枚は置き場にある画像と同じなので、それを使います。": "{n} are the same as images already on the shelf, so those are used. ",
  "{n} 個は使えない形式でした（PNG・JPEG・GIF・WebP が使えます）。": "{n} had a format that cannot be used (PNG, JPEG, GIF and WebP work). ",
  "{n} 枚は 5 MB を超えています。ココフォリアで読み込めないことがあるので、小さくしてから使ってください。": "{n} are over 5 MB. CCFOLIA may not import them, so make them smaller first.",
  "画像の URL（https:// から）": "Image URL (starting with https://)",
  "URL は https:// から始まるものを入れてください。": "Please enter a URL that starts with https://.",
  "名前なし": "no name",
  "話し手・差分: {names}": "Speakers / expressions: {names}",
  "個別に選んだシナリオテキスト {n} 件": "{n} scenario text(s) where it was chosen individually",
  "「{name}」は次の所で使っています。": "\"{name}\" is used here:",
  "削除すると、これらは「画像なし」になります。削除しますか？": "Deleting it leaves these with \"No image\". Delete?",
  "「{name}」を置き場から削除しますか？": "Delete \"{name}\" from the shelf?",
  "削除しました。使っていた所は「画像なし」になりました。": "Deleted. Where it was used is now \"No image\".",
  "削除しました。": "Deleted.",
  "画像なし": "No image",
  "（名前なし）": "(no name)",
  "（URL）": " (URL)",
  "{label}にファイルから画像を追加": "Add an image from a file: {label}",
  "「{name}」の中身が見つかりません。置き場で入れ直してください": "The contents of \"{name}\" are missing. Add it to the shelf again.",
  "「{name}」は {size}。5 MB を超えると、ココフォリアで読み込めないことがあります": "\"{name}\" is {size}. Over 5 MB, CCFOLIA may not import it.",
  "まだ画像がありません。": "No images yet.",
  "中身なし": "missing",
  "画像の名前": "Image name",
  "出典・作者（任意）": "Source / author (optional)",
  "画像「{name}」の出典・作者": "Source / author of the image \"{name}\"",
  "中身が見つかりません": "contents missing",
  "（5 MB 超）": " (over 5 MB)",
  "削除": "Delete",
  "画像「{name}」を削除": "Delete the image \"{name}\"",
  "{name}の立ち絵": "Portrait of {name}",
  "画像をここにドロップしても設定できます": "Dropping an image here sets it too",
  "名前（タイトル）": "Name (title)",
  "台本での書き方（ほかにあれば。「、」区切り）": "Other spellings in the script (comma-separated)",
  "例: ありす、アリー": "e.g. Al, Allie",
  "{n} 人目の話し手を削除": "Delete speaker {n}",
  "「{name}」を削除しますか？（置き場の画像は残ります）": "Delete \"{name}\"? (The shelf's images stay.)",
  "差分の名前（例: 笑顔）": "Expression name (e.g. smile)",
  "{name}の差分の名前": "Expression name for {name}",
  "差分「{label}」の画像": "Image of the expression \"{label}\"",
  "差分「{label}」を削除": "Delete the expression \"{label}\"",
  "＋ 差分（表情）を追加": "+ Add an expression",
  "置き場から差分を作る": "Expressions from the shelf",
  "名前が「{name}_笑顔」のような画像を、差分にします": "Images named like \"{name}_smile\" become expressions",
  "話し手の名前": "speaker name",
  "{name}の立ち絵から演出差分を作る": "Make an effect expression from the portrait of {name}",
  "演出差分を作る…": "Make an effect expression…",
  "ファイルの立ち絵を設定すると使えます（URL の画像は、ブラウザの制限で加工できません）": "Available once a portrait from a file is set (images by URL cannot be edited, a browser restriction)",
  "立ち絵を加工して、差分を作ります": "Makes an expression by altering the portrait",
  "置き場に画像がありません。": "There are no images on the shelf.",
  "置き場の画像は、すべて一覧で使われています。": "Every image on the shelf is already used in the list.",
  "画像 {n} 枚ぶん、シナリオテキストを足しました": "Added scenario texts for {n} image(s)",
  "（一覧で使っている {n} 枚は飛ばしました）": " ({n} already used in the list were skipped)",
  "。本文が空なので、1 件ずつ入れてください。": ". Their text is empty, so fill each one in.",
  "先に、話し手の名前を入れてください。": "Enter the speaker's name first.",
  "新しく作れる差分はありません（すでに作ってあります）。": "There are no new expressions to make (they exist already).",
  "名前が「{name}」で始まる画像が見つかりません。画像の名前を「{name}_笑顔」のようにしてください。": "No image has a name starting with \"{name}\". Name images like \"{name}_smile\".",
  "差分を {n} 個作りました: {names}。": "Made {n} expression(s): {names}. ",
  "立ち絵も設定しました。": "The portrait was set too.",
  "シルエット": "Silhouette",
  "セピア": "Sepia",
  "モノクロ": "Monochrome",
  "ぼかし": "Softness",
  "半透明": "Translucent",
  "このブラウザでは、この効果は使えません": "this browser cannot do this effect",
  "画像を書き出せませんでした": "the image could not be written",
  "先に、この話し手の立ち絵を設定してください。": "Set this speaker's portrait first.",
  "URL の画像は、ブラウザの制限で加工できません。ファイルの画像で試してください。": "Images by URL cannot be edited (a browser restriction). Try with an image from a file.",
  "すでに「{label}」の差分があります。": "There is already an expression \"{label}\".",
  "この画像は背景が透明ではないので、四角い黒い塊になります。背景が透明な PNG の立ち絵で試してください。": "This image has no transparent background, so it would become a black rectangle. Try a PNG portrait with a transparent background.",
  "差分「{label}」を作りました（画像は置き場に入っています）。台本に「{name}（{label}）「…」」と書くと使えます。": "Made the expression \"{label}\" (its image is on the shelf). Write {name} ({label}) \"…\" in the script to use it.",
  "名前": "Name",
  "ただし 5 MB を超えています。ココフォリアで読み込めないことがあります。": " It is over 5 MB, though; CCFOLIA may not import it.",
  "演出差分を作れませんでした: ": "Could not make the effect expression: ",
  "登録していない話し手がいます（立ち絵なしで、台本の名前のまま送られます）: ": "Some speakers are not registered (they are sent without a portrait, under the name in the script): ",
  "＋「{name}」を話し手に追加": "+ Add \"{name}\" as a speaker",
  "登録していない差分があります（基本の立ち絵で送られます）: ": "Some expressions are not registered (the basic portrait is sent): ",
  "＋「{name}」を差分に追加": "+ Add \"{name}\" as an expression",
  "上に文章を貼ると、ここに 1 件ずつ並びます": "Paste text above and the entries line up here",
  "＋": "+",
  "（名前の欄）": "(name field)",
  "個別の画像": "own image",
  "未登録": "unregistered",
  "差分なし": "no such expression",
  "見出しの前": "before headings",
  "画像つき <b>{a}</b> 件・なし <b>{b}</b> 件": "<b>{a}</b> with an image, <b>{b}</b> without",
  "立ち絵は 幅 {w}px × 高さ {h}px で出ます（元の画像 {iw}×{ih}）。": "The portrait is shown {w} px wide × {h} px high (original image {iw}×{ih}). ",
  "横長の画像は、幅が決まっているので小さく出ます。": "A wide image comes out small because the width is fixed.",
  "縦に長い画像は、画面の高さによって、上が切れます。": "A very tall image may be cut off at the top, depending on the screen height.",
  "画像を読み込んでいます…": "Loading the image…",
  "画像を読み込めませんでした（URL の画像は、リンク切れのことがあります）。": "The image could not be loaded (an image by URL may be a dead link).",
  "この件に画像はありません。": "This entry has no image.",
  "（送るときの名前の欄の名前）": "(the name in the name field when sending)",
  "（名前の欄の名前）": "(the name in the name field)",
  "（立ち絵なし）": " (no portrait)",
  "基本": "Basic",
  "（未登録）": " (unregistered)",
  "自動（話し手・差分・同じ名前の画像）": "Auto (speaker, expression, or the image with the same name)",
  "（新しいシナリオテキスト）": "(new scenario text)",
  "手直しした内容を捨てて、文章から一覧を作り直しますか？": "Discard your edits and rebuild the list from the text?",
  "文章から作り直しました。": "Rebuilt from the text.",
  "見出しより前の文の名前": "Name for text before the first heading",
  "本文（見出しで区切る）": "Text (split at headings)",
  "■図書館\n古い新聞が並んでいる。\n\n■書斎\n机の上に鍵がある。": "■ Library\nOld newspapers line the shelves.\n\n■ Study\nThere is a key on the desk.",
  "アリス「こんにちは。」\nボブ「やあ。」\n扉の向こうから足音が近づいてくる。": "Alice \"Hello.\"\nBob \"Hi.\"\nFootsteps approach from beyond the door.",
  "見出し": "Title",
  "：": ": ",
  "確定しました（{n} 件）。次の文章を入れられます。": "Confirmed ({n}). You can enter the next text.",
  "戻しました。入っていた文章は、確定したものの最後に移しました。": "Put back. The text that was there was moved to the end of the confirmed ones.",
  "戻しました。直したら、もう一度「確定」してください。": "Put back. When you have fixed it, \"Confirm\" again.",
  "{n} 件": "{n}",
  "{n} 番目を上へ": "Move number {n} up",
  "{n} 番目を下へ": "Move number {n} down",
  "戻して直す": "Put back to edit",
  "{n} 番目を削除": "Delete number {n}",
  "確定した {n} 番目（{count} 件）を削除しますか？": "Delete confirmed number {n} ({count})?",
  "確定 <b>{done}</b> 件 ＋ 今の一覧 <b>{now}</b> 件 ＝ <b>{total}</b> 件を 1 つの ZIP に書き出します。": "<b>{done}</b> confirmed + <b>{now}</b> in the current list = <b>{total}</b> go into one ZIP.",
  "今の一覧 <b>{now}</b> 件を ZIP に書き出します。": "The <b>{now}</b> in the current list go into a ZIP.",
  "書き出すシナリオテキストがまだありません。": "There are no scenario texts to export yet.",
  "（使っていません）": "(not used)",
  "、ほか {n} 種": ", and {n} more",
  "ZIP を作る部品を読み込めませんでした。ネットにつながった状態で開き直してください。": "The part that makes ZIP files could not be loaded. Open the page again while online.",
  "まとめる画像がありません。": "There are no images to save.",
  "ZIP を作っています…": "Making the ZIP…",
  "シナリオテキストメーカー 画像の一覧": "Scenario Text Maker - image list",
  "作成: {date}": "Made: {date}",
  "画像 {n} 枚（{scope}）": "{n} image(s) ({scope})",
  "置き場のすべて": "everything on the shelf",
  "シナリオテキストで使っているもの": "those used by scenario texts",
  "画像ファイルは images フォルダに入っています。": "The image files are in the images folder.",
  "「ルームデータ内の名前」は、書き出したルームデータ（ZIP）の中での、その画像のファイル名です。": "\"Name in the room data\" is the file name of the image inside the exported room data (ZIP).",
  "（未記入）": "(not given)",
  "    出典・作者: {credit}": "    Source / author: {credit}",
  "    使っている所: {where}": "    Used by: {where}",
  "（URL の画像。中身は入っていません）": " (an image by URL; its contents are not included)",
  "（中身が見つからないので、入っていません）": " (its contents are missing, so it is not included)",
  "（{n}）": " ({n})",
  "    大きさ: {size}（{type}）": "    Size: {size} ({type})",
  " ※ 5 MB を超えています": " * over 5 MB",
  "    ルームデータ内の名前: {name}": "    Name in the room data: {name}",
  "画像の一覧.txt": "image-list.txt",
  "画像 {n} 枚を {name}（{size}）にまとめて保存しました。": "Saved {n} image(s) together as {name} ({size}). ",
  "URL の画像 {n} 件は、一覧に URL だけ書きました。": "For {n} image(s) by URL, only the URL is in the list. ",
  "中身が見つからない画像が {n} 枚あります。": "The contents of {n} image(s) are missing.",
  "画像をまとめられませんでした: ": "Could not save the images: ",
  "このブラウザでは ZIP を作れません（https のページか、新しい Chrome・Edge で開いてください）。": "This browser cannot make the ZIP (open the https page, or use a recent Chrome or Edge).",
  "本文が空のシナリオテキストがあります（{where}）。ココフォリアでは送信欄の文が代わりに送られてしまうので、本文を入れるか削除してください。": "A scenario text has no text ({where}). CCFOLIA would send whatever is in the chat box instead, so give it a text or delete it.",
  "確定した {n} 番目": "confirmed number {n}",
  "今の一覧": "the current list",
  "画像「{name}」の中身が見つかりません。置き場で入れ直すか、使っている所の画像を変えてください。": "the contents of the image \"{name}\" are missing. Add it to the shelf again, or change the image where it is used.",
  "書き出しました（シナリオテキスト {n} 件・画像 {files} 枚）。ココフォリアのルーム設定からインポートしてください。": "Exported ({n} scenario text(s), {files} image(s)). Import it from CCFOLIA's room settings. ",
  "5 MB を超える画像が {n} 枚あり、ココフォリアで読み込めないことがあります。": "{n} image(s) are over 5 MB and CCFOLIA may not import them.",
  "ZIP を作れませんでした: ": "Could not make the ZIP: ",
  "前の版で設定した画像 {n} 枚を、画像の置き場に移しました。": "{n} image(s) set in an earlier version were moved to the image shelf.",
  "このブラウザでは画像を保存できません。画像を使うときは「プロジェクトを保存」でファイルに残してください。": "This browser cannot keep images. When you use images, save them to a file with \"Save project\".",
  "URL の画像を置き場に入れました。": "The image by URL was put on the shelf.",
  "画像は「画像の置き場」の枠か、話し手の画像の所にドロップしてください。": "Drop images on the \"Image shelf\" box or on a speaker's image.",
  "今の文章を例で置き換えますか？": "Replace the current text with the example?",
  "プロジェクトを保存しました（置き場の画像も入っています）。": "Project saved (the shelf's images are included).",
  "プロジェクトを保存できませんでした: ": "Could not save the project: ",
  "プロジェクトを開きました。": "Project opened. ",
  "画像 {n} 枚を置き場に入れました。": "{n} image(s) were put on the shelf.",
  "プロジェクトファイルを読めませんでした。": "Could not read the project file.",
  "話し手と文章、確定したものをすべて消して、最初からやり直しますか？（画像の置き場は残ります）": "Clear the speakers, the text and everything confirmed, and start over? (The image shelf stays.)",
  "最初からにしました。": "Started over.",

  // ---- i18n.v1.js
  "訳の誤りを知らせる": "Report a translation error",
});
